/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zedrl.views;

/**
 *
 * @author Brandon
 */
public class StatusMessagePanel extends javax.swing.JPanel {

    /**
     * Creates new form StatusMessagePanel
     */
    public StatusMessagePanel() {
        initComponents();
    }
    
    public void printStatus(String status){
        if(StatusArea.getLineCount() > 10){
            StatusArea.setText("");
        }
        StatusArea.append(status + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StatusArea = new javax.swing.JTextArea();

        setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N

        StatusArea.setBackground(new java.awt.Color(0, 0, 0));
        StatusArea.setColumns(20);
        StatusArea.setForeground(new java.awt.Color(255, 255, 255));
        StatusArea.setRows(5);
        StatusArea.setFocusable(false);
        jScrollPane1.setViewportView(StatusArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea StatusArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
