/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zedrl.views;

import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import squidpony.squidgrid.gui.swing.SwingPane;

/**
 *
 * @author Brandon
 */
public class SwingHelpScreen extends javax.swing.JPanel implements Screen {
    
    JFrame frame;
    /**
     * Creates new form SwingHelpScreen
     */
    public SwingHelpScreen(JFrame frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setFocusable(false);
        text.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayOutput(SwingPane display) {
        display.setVisible(false);
        this.setBounds(display.bounds());
        frame.add(this);
        StyledDocument doc = text.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        text.setText("");
        text.setText("Welcome to ZedRL!  If this is your first time playing a roguelike, the following instructions should be useful:\n\n\n"
                + "Use the numpad, directional, or VI keys to move the hero\n"
                + "Use [ g ] or [ , ] to pick items up from the dungeon\n"
                + "Use [ w ] to wield or wear weapons and armor\n"
                + "Use [ d ] to drop or unequip items\n"
                + "Use [ t ] to throw an item or weapon from your inventory\n"
                + "Use [ x ] to examine items in your inventory\n"
                + "Use [ ; ] to look around the dungeon\n"
                + "Finally, you can press [?] to return to this help page\n\n\n"
                + "--[Press [ESC] to return to the game]--");
    }

    @Override
    public Screen respondToUserInput(KeyEvent key) {
        if(key.getKeyCode() == key.VK_ESCAPE){
            frame.remove(this);
            return null;
        }else{
            return this;
        }
    }
}
